### ISSUE TITLE
can't compile lineageos 16!

### ISSUE THREAD

**Issue by ghost** [SonyCustoms/device_sony_tuba#3]
I'm using these commands to reproduce error:
> . build/envsetup.sh
lunch full_tuba-eng
mka

then error occurred:

> DANiO /mnt/.sda1/home/daniel/Desktop/lineage # mka
build/make/core/combo/TARGET_linux-arm.mk:43: warning: cortex-a53 is armv8-a.
build/make/core/combo/TARGET_linux-arm.mk:45: warning: TARGET_2ND_ARCH_VARIANT, armv7-a-neon, ignored! Use armv8-a instead.
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
LINEAGE_VERSION=16.0-20190210-UNOFFICIAL-
TARGET_PRODUCT=full_tuba
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a53
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=cortex-a53
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.18.16-aufs-x86_64-Linux
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ2A.190205.001
OUT_DIR=/mnt/.sda1/home/daniel/Desktop/lineage/out
============================================
[1/1] /mnt/.sda1/home/daniel/Desktop/lineage/out/soong/.minibootstrap/minibp /mnt/.sda1/home/daniel/Desktop/lineage/out/soong/.bootstrap/build.ninja
[55/56] glob prebuilts/ndk/stl.bp
[80/80] /mnt/.sda1/home/daniel/Desktop/lineage/out/soong/.bootstrap/bin/soong_build /mnt/.sda1/home/daniel/Desktop/lineage/out/soong/build.ninja
FAILED: /mnt/.sda1/home/daniel/Desktop/lineage/out/soong/build.ninja
/mnt/.sda1/home/daniel/Desktop/lineage/out/soong/.bootstrap/bin/soong_build -t -l /mnt/.sda1/home/daniel/Desktop/lineage/out/.module_paths/Android.bp.list -b /mnt/.sda1/home/daniel/Desktop/lineage/out/soong -n /mnt/.sda1/home/daniel/Desktop/lineage/out -d /mnt/.sda1/home/daniel/Desktop/lineage/out/soong/build.ninja.d -o /mnt/.sda1/home/daniel/Desktop/lineage/out/soong/build.ninja Android.bp
error: vendor/lineage/build/soong/Android.bp:31:8: module "generated_kernel_includes": cmd: unknown variable '$(KERNEL_MAKE_FLAGS)'
ninja: build stopped: subcommand failed.

**Comment by ghost** [comment]
btw: this is also occurring in the lineageos 15.1 repo.

**Comment by andrwgldmn** [comment]
> 
> 
> btw: this is also occurring in the lineageos 15.1 repo.

idk what are you talking about. I have made some builds of oreo without any troubles. But its not booting, some fixes needed for hwc lib..

**Comment by andrwgldmn** [comment]
and fuck pie and oreo roms for this moment due to bug with RIL, IMO

**Comment by andrwgldmn** [comment]
try to use `mka bacon`

**Comment by andrwgldmn** [comment]
so I think that we should fix ril and then try to have +- oreo and pie roms.
and do you have telegram or FB acc?

**Comment by ghost** [comment]
here you can chat with me: https://www.facebook.com/World.Of.DANiO
I will not give my private fb.

**Comment by ghost** [comment]
i can help you

**Comment by andrwgldmn** [comment]
so. make forks, make usefull and pretested PR`s :)

**Comment by ghost** [comment]
pretested pr's? what is?

**Comment by andrwgldmn** [comment]
You make fork, make some changes, test it, make pull request :)
